apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-deployment
  labels:
    app: spring-boot-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-boot-app
  template:
    metadata:
      labels:
        app: spring-boot-app
    spec:
      containers:
        - image: atamankina/spring-boot-app-test:latest
          imagePullPolicy: Always
          name: spring-boot-webserver
          ports:
            - containerPort: 8080
